### ISSUE TITLE
Uncaught ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.Atom#42]
[Enter steps to reproduce below:]

1. Open fsharp/FSharpMDXS/MonoDevelop.FSharpBinding with FSharpUnitTestTextEditor.fs
2. Close atom and reopen

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [FSharp](https://github.com/fsprojects/FSharp.Atom) package, v0.1.14

### Stack Trace

Uncaught ReferenceError: fs is not defined

```
At /Users/dave/.atom/packages/FSharp/lib/fsharp.js:827

ReferenceError: fs is not defined
    at FSharpIDE__projInit$ (/Users/dave/.atom/packages/FSharp/lib/fsharp.js:827:15)
    at FSharpIDE__initialize$ (/Users/dave/.atom/packages/FSharp/lib/fsharp.js:785:5)
    at /Users/dave/.atom/packages/FSharp/lib/fsharp.js:762:14
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "autocomplete"
    ],
    "themes": [
      "atom-dark-ui",
      "cobalt"
    ]
  }
}
```

### Installed Packages

```coffee
# User
FSharp, v0.1.14
cobalt, v0.5.0
color-picker, v1.7.0
highlight-selected, v0.9.2
language-csharp, v0.5.0
language-fsharp, v0.8.4
select-rectangle, v1.0.2

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.1.15`
